FROM node:16.13.0

USER root

RUN apt-get -y update 

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000

RUN chmod 777 /app/node_modules/*/*

CMD ["npm","start"]

